# Site settings
title: Júnior César Abreu - Desenvolvedor Mobile e Front End
description: Um blog sobre programação para aprendizado
baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "http://localhost:3000"
url: "http://juniorcesarabreu.tk" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: juniorcesarabreu
user_description: isto é um blog, eu acho
email: juniorabreuantispam@outlook.com
twitter_username: juniorcesarsg
github_username:  juniorcesarabreu
gplus_username:  lorem_ipsum
disqus_username: juniorcesarabreu
fb_username: juniorcesarabreu.sg
stack_username: juniorcesarabreu
linkedin_username: juniorcesarabreu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: https://juniorcesarabreu.tk/,
    external: true

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
